// <auto-generated />
using System;
using IwasBahaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IwasBahaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

            modelBuilder.Entity("IwasBahaAPI.Models.RoadStatusModels+Road", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoadStatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoadStatusId");

                    b.ToTable("Roads");
                });

            modelBuilder.Entity("IwasBahaAPI.Models.RoadStatusModels+RoadStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barangay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoadStatusUpdateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoadStatusUpdateId");

                    b.ToTable("RoadStatuses");
                });

            modelBuilder.Entity("IwasBahaAPI.Models.RoadStatusModels+RoadStatusUpdate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RoadStatusUpdates");
                });

            modelBuilder.Entity("IwasBahaAPI.Models.RoadStatusModels+Road", b =>
                {
                    b.HasOne("IwasBahaAPI.Models.RoadStatusModels+RoadStatus", null)
                        .WithMany("Roads")
                        .HasForeignKey("RoadStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IwasBahaAPI.Models.RoadStatusModels+RoadStatus", b =>
                {
                    b.HasOne("IwasBahaAPI.Models.RoadStatusModels+RoadStatusUpdate", null)
                        .WithMany("Statuses")
                        .HasForeignKey("RoadStatusUpdateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IwasBahaAPI.Models.RoadStatusModels+RoadStatus", b =>
                {
                    b.Navigation("Roads");
                });

            modelBuilder.Entity("IwasBahaAPI.Models.RoadStatusModels+RoadStatusUpdate", b =>
                {
                    b.Navigation("Statuses");
                });
#pragma warning restore 612, 618
        }
    }
}
